baseURL = "/"
languageCode = "de-de"
title = "Robin Bruch"
disableKinds = ["section", "categories"]
disqusShortname = ""
pygmentsCodeFences = false
pygmentsUseClasses = false
paginate = 999
minify = true


[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Author]
  name = "Robin Bruch"

[params]
  description = "Robin Bruch schreibt Texte über Internet, Kultur und Gesellschaft, aber auch über Wichtiges."
  subtitle = "schreibt …"
  author = "Robin Bruch"
  copyright = "Robin Bruch © 2023"
  logo = ""

[frontmatter]
  date  = [":filename", ":default"]
  author = "Robin Bruch"
  github = "https://github.com/r0bing"
  facebook = ""
  og_image = ""
  sitename = ""
  twitter = ""

[permalinks]
  essays = "/:filename"
  journal = "/:year/:month/:day/:filename"
  pages = "/:slug"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
 [[menu.main]]
    identifier = "journal"
    name       = "journal"
    url        = "/"
    weight     = -112

[[menu.main]]
    identifier = "essays"
    name       = "essays"
    url        = "/essays"
    weight     = -111

  [[menu.footer]]
    identifier = "impressum"
    name       = "Impressum"
    url        = "/impressum/"
    weight     = -111

  [[menu.footer]]
    identifier = "datenschutz"
    name       = "Datenschutz"
    url        = "/datenschutz/"
    weight     = -20